events { worker_connections 1024; }

http {
    server {
        listen 80;

        # Твой основной сервис продуктов
        location /api/products {
            proxy_pass http://products-svc-s14:8223;
            proxy_set_header Host $host;
        }

        # Сервис заказов
        location /api/orders {
            proxy_pass http://orders-service:8224;
            proxy_set_header Host $host;
        }

        # Общий healthcheck
        location /health {
            proxy_pass http://products-svc-s14:8223/health;
        }
    }
}